### ISSUE TITLE
install jupyter as a service

### ISSUE THREAD

**Issue by albertogalan** [albertogalan/jupyter#3]
Install jupyter and all it dependencies
has problems if try to install as become : yes , with become_user works otherwise pip cannot install packages. the main packages are those three bellow
```
- name: install pip jupyter libraries
  become_user: "{{jupyter_user}}"
  pip:
    name: "{{item}}"
    state: present
    executable: pip3
  with_items:
     - ipython[all]
     - jupyter
     - jupyter_core
```
